# Generated by Django 6.0.6 on 2026-07-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('niche', models.CharField(max_length=100)),
                ('follower_count', models.IntegerField()),
                ('engagement_rate', models.FloatField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_links', to='accounts.agency')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_links', to='creators.creator')),
            ],
            options={
                'unique_together': {('agency', 'creator')},
            },
        ),
    ]
