# Generated by Django 6.0.6 on 2026-07-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencylink',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='follower_count',
            field=models.PositiveIntegerField(),
        ),
    ]
